(define (problem sokoban-9-9)
(:domain sokoban)
(:objects
	p1 - player
	A B C D E F G H I J K L M N O P Q R S T U V W X Y Z AA AB AC AD AE AF AG AH AI AJ AK AL AM AN AO AP AQ AR AS AT AU AV - pos
)
(:INIT
	(isempty A)
	(isempty B)
	(iswall C)
	(iswall D)
	(iswall E)
	(iswall F)
	(isempty G)
	(isempty H)
	(iswall I)
	(isempty J)
	(isempty K)
	(iswall L)
	(iswall M)
	(iswall N)
	(iswall O)
	(isempty P)
	(isempty Q)
	(iswall R)
	(iswall S)
	(isempty T)
	(isempty U)
	(iscrate V)
	(isempty W)
	(iswall X)
	(iswall Y)
	(isempty Z)
	(iswall AA)
	(ison p1 AB)
	(isempty AC)
	(iswall AD)
	(iswall AE)
	(isempty AF)
	(iscrate AG)
	(iscrate AH)
	(isempty AI)
	(iswall AJ)
	(iswall AK)
	(iswall AL)
	(isempty AM)
	(isempty AN)
	(isempty AO)
	(iswall AP)
	(isempty AQ)
	(iswall AR)
	(iswall AS)
	(iswall AT)
	(iswall AU)
	(iswall AV)
	(Vlink A G)
	(Hlink A B)
	(Vlink B H)
	(Hlink B A)
	(Hlink B C)
	(Vlink C I)
	(Hlink C B)
	(Hlink C D)
	(Vlink D J)
	(Hlink D C)
	(Hlink D E)
	(Vlink E K)
	(Hlink E D)
	(Hlink E F)
	(Vlink F L)
	(Hlink F E)
	(Vlink G A)
	(Vlink G M)
	(Hlink G H)
	(Vlink H B)
	(Vlink H N)
	(Hlink H G)
	(Hlink H I)
	(Vlink I C)
	(Vlink I O)
	(Hlink I H)
	(Hlink I J)
	(Vlink J D)
	(Vlink J P)
	(Hlink J I)
	(Hlink J K)
	(Vlink K E)
	(Vlink K Q)
	(Hlink K J)
	(Hlink K L)
	(Vlink L F)
	(Vlink L R)
	(Hlink L K)
	(Vlink M G)
	(Vlink M S)
	(Hlink M N)
	(Vlink N H)
	(Vlink N T)
	(Hlink N M)
	(Hlink N O)
	(Vlink O I)
	(Vlink O U)
	(Hlink O N)
	(Hlink O P)
	(Vlink P J)
	(Vlink P V)
	(Hlink P O)
	(Hlink P Q)
	(Vlink Q K)
	(Vlink Q W)
	(Hlink Q P)
	(Hlink Q R)
	(Vlink R L)
	(Vlink R X)
	(Hlink R Q)
	(Vlink S M)
	(Vlink S Y)
	(Hlink S T)
	(Vlink T N)
	(Vlink T Z)
	(Hlink T S)
	(Hlink T U)
	(Vlink U O)
	(Vlink U AA)
	(Hlink U T)
	(Hlink U V)
	(Vlink V P)
	(Vlink V AB)
	(Hlink V U)
	(Hlink V W)
	(Vlink W Q)
	(Vlink W AC)
	(Hlink W V)
	(Hlink W X)
	(Vlink X R)
	(Vlink X AD)
	(Hlink X W)
	(Vlink Y S)
	(Vlink Y AE)
	(Hlink Y Z)
	(Vlink Z T)
	(Vlink Z AF)
	(Hlink Z Y)
	(Hlink Z AA)
	(Vlink AA U)
	(Vlink AA AG)
	(Hlink AA Z)
	(Hlink AA AB)
	(Vlink AB V)
	(Vlink AB AH)
	(Hlink AB AA)
	(Hlink AB AC)
	(Vlink AC W)
	(Vlink AC AI)
	(Hlink AC AB)
	(Hlink AC AD)
	(Vlink AD X)
	(Vlink AD AJ)
	(Hlink AD AC)
	(Vlink AE Y)
	(Vlink AE AK)
	(Hlink AE AF)
	(Vlink AF Z)
	(Vlink AF AL)
	(Hlink AF AE)
	(Hlink AF AG)
	(Vlink AG AA)
	(Vlink AG AM)
	(Hlink AG AF)
	(Hlink AG AH)
	(Vlink AH AB)
	(Vlink AH AN)
	(Hlink AH AG)
	(Hlink AH AI)
	(Vlink AI AC)
	(Vlink AI AO)
	(Hlink AI AH)
	(Hlink AI AJ)
	(Vlink AJ AD)
	(Vlink AJ AP)
	(Hlink AJ AI)
	(Vlink AK AE)
	(Vlink AK AQ)
	(Hlink AK AL)
	(Vlink AL AF)
	(Vlink AL AR)
	(Hlink AL AK)
	(Hlink AL AM)
	(Vlink AM AG)
	(Vlink AM AS)
	(Hlink AM AL)
	(Hlink AM AN)
	(Vlink AN AH)
	(Vlink AN AT)
	(Hlink AN AM)
	(Hlink AN AO)
	(Vlink AO AI)
	(Vlink AO AU)
	(Hlink AO AN)
	(Hlink AO AP)
	(Vlink AP AJ)
	(Vlink AP AV)
	(Hlink AP AO)
	(Vlink AQ AK)
	(Hlink AQ AR)
	(Vlink AR AL)
	(Hlink AR AQ)
	(Hlink AR AS)
	(Vlink AS AM)
	(Hlink AS AR)
	(Hlink AS AT)
	(Vlink AT AN)
	(Hlink AT AS)
	(Hlink AT AU)
	(Vlink AU AO)
	(Hlink AU AT)
	(Hlink AU AV)
	(Vlink AV AP)
	(Hlink AV AU)
	)
(:goal
	(AND (iscrate Q) (iscrate V) (iscrate AH))
)
)
